// Interface for the nested object
interface CategoryData {
  [key: string]: string[];
}

// Main interface for the sidebarData
export interface SidebarDataObject {
  [key: string]: CategoryData;
}

export const sidebarData: SidebarDataObject = {
  Headsets: {
    "Popular Shopping Ideas": ["Video Game", "Wireless", "Desktop", "Animal"],
    Department: [
      "PC Game Headsets",
      "PlayStation 4 Headsets",
      "PlayStation 5 Headsets",
      "Xbox One Headsets",
      "Mac Game Headsets",
      "Xbox Series X & S Accessories",
      "Nintendo Switch Accessories",
      "PlayStation Accessories",
    ],
    "Customer Review": [],
    Brands: [
      "Logitech G",
      "Razer",
      "Turtle Beach",
      "SteelSeries",
      "HyperX",
      "Corsair",
      "Sony",
      "JBL",
      "ASTRO Gaming",
      "BENGOO",
      "Skullcandy",
      "Sennheiser",
      "NUBWO",
      "Logitech",
      "ASUS",
      "HP",
      "FIFINE",
      "EPOS",
      "Redragon",
      "PDP",
      "Gtheos",
      "Lenovo",
      "acer",
    ],
    Price: [],
    "Deals & Discounts": ["All Discounts", "Today's Deals"],
    Condition: ["New", "Used"],
    "New Releases": ["Last 90 days"],
    Seller: [
      "Amazon.com",
      "Amazon Warehouse",
      "HoSEN",
      "Triplenet Pricing INC",
      "RAREWAVES-IMPORTS",
      "M + L",
      "Playvital",
    ],
  },
  Keyboards: {
    "Popular Shopping Ideas": [
      "Wireless",
      "Mechanical",
      "Console",
      "Ergonomic",
      "Backlit",
      "Portable",
      "Retro",
      "Clicky",
    ],
    Department: [
      "PC Gaming Keyboards",
      "Mac Games & Accessories",
      "Mac Gaming Keyboards",
      "Xbox Games, Consoles & Accessories",
      "Xbox Accessories",
    ],
    "Customer Review": [],
    Brands: [
      "Logitech G",
      "Razer",
      "SteelSeries",
      "Corsair",
      "Redragon",
      "ASUS",
      "MageGee",
      "HyperX",
      "Lenovo",
      "RK ROYAL KLUDGE",
      "Keychron",
      "AULA",
      "Snpurdiri",
      "CHONCHOW",
      "Logitech",
      "Womier",
      "YUNZII",
      "DIERYA",
      "NPET",
    ],
    Price: [],
    "Deals & Discounts": ["All Discounts", "Today's Deals"],
    Condition: ["New", "Used"],
    "New Releases": ["Last 90 days"],
    Seller: [
      "EPOMAKER",
      "Amazon.com",
      "Triplenet Pricing INC",
      "Redragon Shop",
      "Yunzii Keyboard",
      "Ranked llc",
    ],
  },
  "Computer mice": {
    "Popular Shopping Ideas": [
      "Wireless",
      "Ergonomic Design",
      "Lightweight",
      "Honeycomb",
      "Rechargeable",
      "Soundless",
    ],
    Department: [
      "PC Gaming Mice",
      "Mac Games & Accessories",
      "Mac Gaming Mice",
      "Computer Mice",
    ],
    "Customer Review": [],
    Brands: [
      "Logitech G",
      "Razer",
      "Corsair",
      "Redragon",
      "ASUS",
      "SteelSeries",
      "HyperX",
      "EVGA",
      "Glorious",
      "Logitech",
      "Pulsar Gaming Gears",
      "acer",
      "Thermaltake",
      "BenQ",
      "Cooler Master",
      "Rapoo",
      "ROCCAT",
      "EPOMAKER",
      "FIRSTBLOOD ONLY GAME.",
      "UHURU",
      "Lenovo",
    ],
    Price: [],
    "Deals & Discounts": ["All Discounts", "Today's Deals"],
    Condition: ["New", "Used"],
    "New Releases": ["Last 30 days", "Last 90 days", "Coming Soon"],
    Seller: [
      "Amazon.com",
      "Amazon Warehouse",
      "Triplenet Pricing INC",
      "M + L",
      "LZYDD Store",
      "RAREWAVES-IMPORTS",
      "Amazon Japan",
    ],
  },
  Chairs: {
    "Popular Shopping Ideas": [
      "Office",
      "Polycarbonate",
      "Ergonomic",
      "Leather",
      "Mesh",
      "Desk",
      "Heavy Duty",
      "Fortnite",
      "Memory Foam",
      "Swivel",
    ],
    Department: [
      "Gaming Chairs",
      "Video Game Chairs",
      "Computer Gaming Chairs",
      "Office Chairs",
      "Home Office Desk Chairs",
    ],
    "Customer Review": [],
    Brands: [
      "GTRACING",
      "BestOffice",
      "X Rocker",
      "COLAMY",
      "AutoFull",
      "OLIXIS",
      "OSP Home Furnishings",
      "MoNiBloom",
      "Anda Seat",
      "Ticova",
    ],
    Price: [],
    "Deals & Discounts": ["All Discounts", "Today's Deals"],
    Condition: ["New", "Used"],
    "New Releases": ["Last 90 days"],
    Seller: [
      "Amazon.com",
      "PENG YONG HOME",
      "Xingyuan shop",
      "黄总-shop",
      "AMZ-SPQHHG-SHOP",
      "Zatren",
      "LI JING US",
    ],
  },
};
